import { JColors } from "./contextTypes";

const generalStyles = {
    radius: "0.5rem",
};

export const lightThemeColors: JColors = {
    ...generalStyles,
    background: "#FFFFFF",
    foreground: "#171E23",
    card: "#FFFFFF",
    cardForeground: "#F4F4F9",
    popover: "#FFFFFF",
    popoverForeground: "#F4F4F9",
    primary: "#3196E2",
    primaryForeground: "#FEF4F2",
    secondary: "#F3F3FC",
    secondaryForeground: "#F4F4F9",
    muted: "#F3F3FC",
    mutedForeground: "#A8B3C0",
    accent: "#F3F3FC",
    accentForeground: "#171E23",
    destructive: "#E43339",
    destructiveForeground: "#FBFBFB",
    border: "#F3F3FC",
    input: "#F3F3FC",
    ring: "#3196E2",
};
export const darkThemeColors: JColors = {
    ...generalStyles,
    background: "#2B2E34",
    foreground: "#FBFBFB",
    card: "#282E31",
    cardForeground: "#0F0F17",
    popover: "#171717",
    popoverForeground: "#0F0F17",
    primary: "#1D8BCB",
    primaryForeground: "#26261A",
    secondary: "#3C3C40",
    secondaryForeground: "#0F0F17",
    muted: "#0F0F17",
    mutedForeground: "#A4A4B0",
    accent: "#2D333D",
    accentForeground: "#FBFBFB",
    destructive: "#A8363B",
    destructiveForeground: "#FAF2F1",
    border: "#3C3C40",
    input: "#3C3C40",
    ring: "#1D8CC0",
};
